from .iRepositorioMatricula import IRepositorioMatricula
from .iRepositorioCadeira import IRepositorioCadeira
from .iRepositorioConta import IRepositorioConta

from .factories import SQLAlchemyRepositorioFactory, ListRepositorioFactory