version: '3'
services:
  cadeiraservice:
    build:
      context: ./backendCadeira
    ports:
      - "5001:5001"
    volumes:
      - ./backendCadeira:/app
    environment:
      - AUTO_UPDATE=true

  matriculaservice:
    build:
      context: ./backendMatricula
    ports:
      - "5002:5002"
    volumes:
      - ./backendMatricula:/app
    environment:
      - AUTO_UPDATE=true

  gatewayservice:
    build:
      context: ./backendGateway
    ports:
      - "5000:5000"

  contaservice:
    build:
      context: ./backendConta
    ports:
      - "5003:5003"
    volumes:
      - ./backendConta:/app
    environment:
      - AUTO_UPDATE=true

networks:
  mynetwork:
