from .controladorConta import ControladorConta
from .controladorCadastroCadeira import ControladorCadastroCadeira
from .controladorRealizarMatricula import ControladorRealizarMatricula
from .controladorVisualizarHorario import ControladorVisualizarHorario
from .controladorOfertaCadeira import ControladorOfertaCadeira