from .controladorLogin import ControladorLogin
from .controladorCadastroCadeira import ControladorCadastroCadeira
from .controladorRealizarMatricula import ControladorRealizarMatricula
from .controladorVisualizarHorario import ControladorVisualizarHorario
from .alunoStrategy import AlunoStrategy
from .professorStrategy import ProfessorStrategy