from .controladorCadastroCadeira import ControladorCadastroCadeira
from .controladorOfertaCadeira import ControladorOfertaCadeira
from .controladorVisualizarHorario import ControladorVisualizarHorario